"""The review as Markdown: what holds for the whole pack, then each creature's findings with their
numbers, ready to hand back to whoever draws the frames, one creature at a time."""
from collections import Counter, OrderedDict
from .checks import LIMITS

TITLES = OrderedDict([
    ('facing', 'Faces the wrong way'),
    ('turned', 'A frame faces the other way'),
    ('off-model', 'Off model (seen by eye)'),
    ('same-leg', 'The same leg always leads'),
    ('pair-size', 'The two strides are different drawings'),
    ('height', 'Changes height when it walks'),
    ('ground', 'Leaves the ground line'),
    ('torso-drift', 'Upper body jitters'),
    ('legs-still', 'Legs barely move'),
    ('edge', 'Touches the canvas edge'),
    ('walk-frames', 'Too few walk frames'),
    ('glide-frames', 'No stride: needs engine motion or four keys'),
])
MENDED = {'facing': 'mirrored by the tool', 'ground': 'moved by the tool', 'torso-drift': 'moved by the tool'}


def markdown(pack, findings, source):
    sprites = pack.sprites()
    counts = Counter(f['check'] for f in findings)
    two = sum(1 for f in findings if f['check'] == 'walk-frames')
    glides = sorted({f['key'] for f in findings if f['check'] == 'glide-frames'})
    lines = [
        '# Creature sprite review', '',
        f'Generated by `python3 tools/sprite_review.py audit` from {source}: {len(sprites)} sprite sets '
        f'({len(pack.items) - len(sprites)} colossi are assemblies, not reviewed here). '
        'Limits are `LIMITS` in `tools/sprites/checks.py`; the by-eye notes are `tools/sprites/notes.json`. '
        'The brief for redrawing, and how to run this again, is `docs/SPRITE_QA.md`.', '',
        '## Across the pack', '',
        f'- **{two} side views walk on two frames** (`move_0`, `move_1`). A profile walk needs '
        f'{LIMITS["side_walk_frames"]}: contact, passing, contact on the other foot, passing. Two frames '
        'snap between the two contacts with nothing between, which reads as a hop or a skate. This is the '
        'main cause of the side views looking wrong, and redrawing the two frames cannot cure it.',
        '- Front and back walks on two frames read acceptably (the legs overlap) and are not flagged for it.',
        f'- **{len(glides)} creatures have no stride** (they slither, ooze, drift or fly) and two move keys: '
        'move them in the engine (a bob, a squash, a sway) or draw four keys: ' +
        ', '.join(f'`{k}`' for k in glides) + '.',
        '',
        '| Check | Findings |', '|---|---|',
    ]
    lines += [f'| {TITLES.get(c, c)} | {counts[c]} |' for c in TITLES if counts[c]]
    lines += ['', '## By creature', '',
              'Each line is one fix to ask for. *(mended)* marks what `fix` does without drawing.', '']
    redraw = {(f['key'], f['direction']) for f in findings if f['check'] == 'off-model'}
    by_key = OrderedDict()
    for f in findings:
        if f['check'] not in ('walk-frames', 'glide-frames'):
            by_key.setdefault(f['key'], []).append(f)
    for item in sprites:
        rows = by_key.get(item['key'])
        if not rows:
            continue
        lines.append(f'### {item.get("display_name", item["key"])} (`{item["key"]}`)')
        lines.append('')
        order = list(TITLES)
        for f in sorted(rows, key=lambda f: (order.index(f['check']) if f['check'] in order else 99, f['direction'])):
            mended = f.get('fix') and f['check'] in MENDED and \
                (f['check'] != 'torso-drift' or (f['key'], f['direction']) not in redraw)
            tag = f' *({MENDED[f["check"]]})*' if mended else ''
            lines.append(f'- **{f["direction"]}**, {TITLES.get(f["check"], f["check"]).lower()}: {f["detail"]}{tag}')
        lines.append('')
    clean = [i['key'] for i in sprites if i['key'] not in by_key]
    lines += ['## Nothing else found (only the frame counts above)', '', ', '.join(f'`{k}`' for k in clean) or 'None.', '']
    return '\n'.join(lines)
