#!/usr/bin/env python3
"""Measures every recorded sound in public/audio (sfx/ and amb/) and writes src/data/sampleLevels.ts:
for each file its length in seconds, its peak and its active RMS in dBFS (the RMS over the stretches
within 40 dB of the peak, so a long silent tail does not make a loud blow read quiet). The sampler
levels each set's takes to one another by it (data/takeTrim.ts), and the tests (tests/soundMix.test.ts)
keep every set in its window. Run again when a recording is added or changed:
`python3 tools/audio_levels.py` (needs `pip install av numpy`)."""
import json, os, sys
import av
import numpy as np

ROOT = os.path.join(os.path.dirname(__file__), '..', 'public', 'audio')

def load(path):
    c = av.open(path)
    rate = c.streams.audio[0].rate
    x = np.concatenate([f.to_ndarray().astype(np.float64) for f in c.decode(audio=0)], axis=1).mean(axis=0)
    c.close()
    return x, rate

def db(v):
    return round(20 * np.log10(max(v, 1e-9)), 1)

out = {}
for d in ('sfx', 'amb'):
    for f in sorted(os.listdir(os.path.join(ROOT, d))):
        if not f.endswith('.mp3'):
            continue
        x, rate = load(os.path.join(ROOT, d, f))
        peak = float(np.abs(x).max())
        win = max(1, int(rate * 0.02))
        n = len(x) // win
        env = np.sqrt((x[: n * win].reshape(n, win) ** 2).mean(axis=1)) if n else np.array([0.0])
        live = env > peak * 0.01  # within 40 dB of the peak
        rms = float(np.sqrt((env[live] ** 2).mean())) if live.any() else 0.0
        out[f'{d}/{f[:-4]}'] = {'sec': round(len(x) / rate, 2), 'peak': db(peak), 'rms': db(rms)}
DEST = os.path.join(os.path.dirname(__file__), '..', 'src', 'data', 'sampleLevels.ts')
with open(DEST, 'w') as fh:
    fh.write('/** What each recording measures (generated by tools/audio_levels.py: run it again when a file in public/audio is added or changed). Data only. */\n\n')
    fh.write('export interface Level {\n  sec: number; // length\n  peak: number; // dBFS\n  rms: number; // dBFS, over the stretches within 40 dB of the peak\n}\n\n')
    fh.write('export const SAMPLE_LEVELS: Readonly<Record<string, Level>> = {\n')
    for k in sorted(out):
        v = out[k]
        fh.write(f"  '{k}': {{ sec: {v['sec']}, peak: {v['peak']}, rms: {v['rms']} }},\n")
    fh.write('};\n')
print(len(out), 'files')
